### ISSUE TITLE
Add a non-functional copy button beside generated password

### ISSUE THREAD

**Issue by syedmazharaliraza** [syedmazharaliraza/IntrepidKey#10]
Add a non-functioning (only html and css) copy button beside generated password similar to this:
![copy](https://user-images.githubusercontent.com/77449219/107261262-1fa3c600-6a65-11eb-80e8-538946328803.PNG)

**Comment by Raghav14200** [comment]
@syedmazharaliraza sir I would like to work on this

**Comment by syedmazharaliraza** [comment]
@Raghav14200 Go ahead bro
