### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [syedmazharaliraza/IntrepidKey#12]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

**Comment by muthuannamalai12** [comment]
I would like to work on it as a part of Cross Woc

**Comment by syedmazharaliraza** [comment]
@muthuannamalai12 Alright go for it
