### ISSUE TITLE
Set the social media icons in one line on the footer

### ISSUE THREAD

**Issue by syedmazharaliraza** [syedmazharaliraza/IntrepidKey#25]
Currently, the social media icons are set as lists 
![footer](https://user-images.githubusercontent.com/77449219/107887343-7741a600-6f2b-11eb-8b85-34579a71673f.PNG)
Arrange them in one line.

**Comment by Devenkapoor7303** [comment]
can i work on this issue

**Comment by syedmazharaliraza** [comment]
@Devenkapoor7303 Go ahead on this one

**Comment by Devenkapoor7303** [comment]
okay

**Comment by kanishkaa24** [comment]
Hey! I would like to work on this issue.
