### ISSUE TITLE
Addition of splash screen

### ISSUE THREAD

**Issue by Sloth-Panda** [syedmazharaliraza/IntrepidKey#28]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
This screen will disappear after few seconds/miliseconds  and will compensate for the loading time
### Have you read the *Contributing Guidelines on Pull Requests* ?

(Write your answer here.)

Yes

**Comment by syedmazharaliraza** [comment]
Sure, Add the logo and the name only. Keep the background that goes well with the colour of the logo
