### ISSUE TITLE
Add a code of conduct.md file

### ISSUE THREAD

**Issue by syedmazharaliraza** [syedmazharaliraza/IntrepidKey#3]
Add a code of conduct.md file to the repository. I can give a sample for the same

**Comment by syedmazharaliraza** [comment]
@96RadhikaJadhav If you are a participant of CWoC than you can surely work on this. But contributions/PRs will be counted after the commencement of the coding phase. No PR will be accepted before it.

**Comment by nilisha-jais** [comment]
I want to work on it

**Comment by syedmazharaliraza** [comment]
@nilisha-jais Sure go ahead

**Comment by kanishkaa24** [comment]
Is this issue still open for grab?

**Comment by syedmazharaliraza** [comment]
@kanishkaa24 It is closed
