### ISSUE TITLE
Fix the responsiveness of the navigation bar

### ISSUE THREAD

**Issue by syedmazharaliraza** [syedmazharaliraza/IntrepidKey#34]
Fix the responsiveness of the navigation bar for tablet and mobile view

**Comment by hansika31** [comment]
can I do this?

**Comment by syedmazharaliraza** [comment]
@hansika31 sure go ahead

**Comment by arbazalam01** [comment]
is this issue still open

**Comment by syedmazharaliraza** [comment]
@arbazalam01 yes you can go ahead with this one. Also join the discord server
