### ISSUE TITLE
Add functionality to generate random numbers in password

### ISSUE THREAD

**Issue by syedmazharaliraza** [syedmazharaliraza/IntrepidKey#46]
write the javascript to generate random numbers in the password when the number checkbox is checked.

**Comment by Amit366** [comment]
@syedmazharaliraza can I work??

**Comment by syedmazharaliraza** [comment]
@Amit366 Assigning one issue at a time buddy

**Comment by pranabprohit** [comment]
Hi, I would like to work on this issue.

**Comment by syedmazharaliraza** [comment]
@pranabprohit Go for it
