### ISSUE TITLE
Fix the responsiveness of the footer

### ISSUE THREAD

**Issue by syedmazharaliraza** [syedmazharaliraza/IntrepidKey#47]
Make the footer responsive to mobile view and tab view

**Comment by Devenkapoor7303** [comment]
Can I work on this issue

**Comment by syedmazharaliraza** [comment]
@Devenkapoor7303 go ahead

**Comment by Deepak8717** [comment]
I can work on this if not completed

**Comment by Devenkapoor7303** [comment]
Yeah you can work on it

**Comment by arbazalam01** [comment]
can i work on this issue

**Comment by syedmazharaliraza** [comment]
@Deepak8717 are you a crosswoc participant?

**Comment by Deepak8717** [comment]
No, I don't know what is that

**Comment by syedmazharaliraza** [comment]
@Deepak8717 Actually these issues are only for crosswoc(an open source program) participants. You can see cwoc label on all issues.

**Comment by jhaashutosh** [comment]
i want to work on this issue.

**Comment by rahil-1407** [comment]
Assign me this issue.

**Comment by arbazalam01** [comment]
can i work on this issue

**Comment by arbazalam01** [comment]
is it still available

**Comment by arbazalam01** [comment]
can i work on it

**Comment by syedmazharaliraza** [comment]
@arbazalam01 Sure
