### ISSUE TITLE
add banner of crosswoc to the readme file

### ISSUE THREAD

**Issue by kmryashasvi** [syedmazharaliraza/IntrepidKey#58]
## 💥 Proposal

I will add banner of crosswoc to the readme file so that, People will know it is associated to crosswoc. Moreover, I will associate link of the crosswoc website to its banner such that, if someone clicks the banner on readme file, it will redirect them to the website of crosswoc.

### Have you read the *Contributing Guidelines on Pull Requests* ?
Yes

**Comment by syedmazharaliraza** [comment]
@kmryashasvi If you want to take up the screenshots in readme issue, then comment there and add all documentation related work under that issue

**Comment by kmryashasvi** [comment]
I think there is a misunderstanding,
under this issue, I am trying to add a poster/banner of "crosswoc"
