### ISSUE TITLE
Functionality to generate random string(password)

### ISSUE THREAD

**Issue by syedmazharaliraza** [syedmazharaliraza/IntrepidKey#8]
Write Javascript code to generate a random string(password), when the **generate** button is clicked. Include **only small alphabets** in the generated string of a **default length of 10 alphabets.**  **Do not** include the **set length feature** as of now.

**Comment by Amit366** [comment]
@syedmazharaliraza sir I would like to work on this issue.

**Comment by syedmazharaliraza** [comment]
@Amit366 Sure.

**Comment by Amit366** [comment]
Should I write the code in html file or js file??

**Comment by syedmazharaliraza** [comment]
@Amit366 Completely up to you.

**Comment by Amit366** [comment]
why did u reopen it??

**Comment by syedmazharaliraza** [comment]
@Amit366 just checking on a few things
