### ISSUE TITLE
Add favicon to the webpage

### ISSUE THREAD

**Issue by syedmazharaliraza** [syedmazharaliraza/IntrepidKey#9]
Add favicon to the webpage. Use favicon generator website that generates all kinds of favicons. Use the Logo.png file.

**Comment by Sloth-Panda** [comment]
Plz assign me as part of cwoc I will be sending prs as soon as the program commence

**Comment by Sloth-Panda** [comment]
@syedmazharaliraza can I provide me with the icon that you want to ass as favicon?
